# Generated by Django 4.1.2 on 2022-10-25 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MailingListSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_site.mailinglist')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guild_site.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_editor', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('subscription', models.ManyToManyField(through='guild_site.MailingListSubscribers', to='guild_site.mailinglist')),
            ],
            options={
                'ordering': ['date_registered'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_site.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_site.siteuser')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_site.siteuser'),
        ),
        migrations.AddField(
            model_name='mailinglistsubscribers',
            name='site_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_site.siteuser'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='subscribers',
            field=models.ManyToManyField(through='guild_site.MailingListSubscribers', to='guild_site.siteuser'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('finalized', models.BooleanField(default=False)),
                ('sending_time', models.DateTimeField(blank=True, null=True)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_site.mailinglist')),
            ],
            options={
                'ordering': ['-finalized', 'sending_time'],
            },
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(editable=False)),
                ('expires', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guild_site.siteuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['post', 'created'], name='guild_site__post_id_d73e17_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['user', '-created'], name='guild_site__user_id_d5b113_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-created'], name='guild_site__categor_08839c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created'], name='guild_site__created_f14547_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='guild_site__user_id_41f86d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailinglistsubscribers',
            unique_together={('mailing_list', 'site_user')},
        ),
    ]
