# Generated by Django 4.1.2 on 2022-10-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
