# Generated by Django 4.1.2 on 2022-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_site', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='finalized',
            field=models.BooleanField(default=False, help_text='Нажмите это чтобы отправить письмо. Иначе письмо считается черновиком.'),
        ),
    ]
