# Generated by Django 4.1.2 on 2022-10-27 17:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild_site', '0004_email_sent_alter_email_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
